Repository directus/app, pull requests merged in 2019-07, with the labels that each got.

#1832 Fix issue #1822 uploading image freezes UI
  src/interfaces/file/input.vue
Labels: bug

#1831 fix issue #1743
  src/interfaces/color-palette/display.vue
Labels: bug

#1817 Update app.vue
  public/index.html
  src/app.vue
Labels: bug, tweak

#1792 Fix some warnings and minor issues with the calendar layout
  src/layouts/calendar/Day.vue
  src/layouts/calendar/Popup.vue
  src/layouts/calendar/layout.vue
Labels: tweak

#1804 Reimagine O2M
  src/interfaces/many-to-many/input.vue
  src/interfaces/one-to-many/input.vue
  src/interfaces/one-to-many/meta.json
  src/routes/item.vue
Labels: tweak

#1853 Reduce listing layout depth
  src/components/items.vue
  src/interfaces/many-to-many/display.vue
Labels: bug, tweak

#1819 Turkish translation v0.2 added
  src/interfaces/activity-icon/meta.json
  src/interfaces/button-group/meta.json
  src/interfaces/calendar/meta.json
  src/interfaces/checkboxes-relational/meta.json
  src/interfaces/checkboxes/meta.json
  src/interfaces/code/meta.json
  src/interfaces/collections/meta.json
  src/interfaces/color/meta.json
  src/lang/tr-TR/index.json
Labels: enhancement

#1880 Fix issue where i18n would merge messages in non initialized languages
  src/store/modules/collections/actions.js
Labels: bug

#1879 Attempt to fix rendering of translated fields
  src/interfaces/translation/input.vue
Labels: bug

#1881 Reimagine files interface
  src/interfaces/files/get-icon.js
  src/interfaces/files/input.vue
  src/interfaces/files/meta.json
  src/interfaces/many-to-many/meta.json
Labels: bug, enhancement

#1868 Update items.vue
  src/components/items.vue
Labels: optimization, tweak

#1893 Allow multiple custom items in checkboxes
  package.json
  src/interfaces/checkboxes/input.vue
Labels: enhancement

#1895 Show image thumbs in item select modal
  src/components/item-select/item-select.vue
  src/components/permissions/permissions-toggle.vue
Labels: enhancement
