Repository directus/app, pull requests merged in 2019-05, with the labels that each got.

#1624 Filter out copies of the main parent item
  src/interfaces/one-to-many/input.vue
Labels: bug

#1626 Fix remaining instances of this.$lodash use
  src/components/install.vue
  src/components/permissions/permissions.vue
Labels: optimization

#1627 Fix rendering height of selects in safari
  src/components/form-inputs/select.vue
  src/components/form-inputs/simple-select.vue
Labels: bug

#1584 Feature: Draggable check boxes
  src/interfaces/checkboxes/display.vue
  src/interfaces/checkboxes/input.vue
  src/interfaces/checkboxes/meta.json
Labels: enhancement

#1646 Don't auto save field setup modal on interface change
  src/components/field-setup.vue
Labels: bug

#1649 Increase strictness of Vue ESLINT plugin
  .eslintrc.js
Labels: optimization

#1647 Update table.vue
  src/components/table/table.vue
Labels: optimization

#1657 Fix #1565 – Hide "Add new" and "Select Existing" buttons when field is Read-only
  src/interfaces/many-to-many/input.vue
  src/interfaces/many-to-many/meta.json
  src/interfaces/one-to-many/input.vue
  src/interfaces/one-to-many/meta.json
Labels: bug

#1658 Reset scroll to the top on navigate
  src/router.js
Labels: bug

#1653 Add allow other option to checkboxes
  src/interfaces/checkboxes/input.vue
  src/interfaces/checkboxes/meta.json
  src/routes/item.vue
Labels: enhancement

#1662 Prevent quill from autofocussing
  src/interfaces/wysiwyg-full/input.vue
Labels: bug

#1663 Width default
  src/components/form/form.vue
  src/routes/settings/collections.vue
Labels: bug

#1664 Fix label not showing up for fields that are created in just the DB
  src/components/form/field.vue
Labels: bug

#1660 Fix #1618 – Labels not clickable in field update modal
  src/components/form-inputs/toggle.vue
Labels: bug

#1665 Handle "0" and 0 values correctly
  src/interfaces/toggle/input.vue
Labels: bug

#1670 Add ability to sort O2M items
  src/interfaces/one-to-many/input.vue
Labels: enhancement

#1673 fix: add latin extended glyphs to font file
  src/assets/fonts/roboto-bold.woff
  src/assets/fonts/roboto-bold.woff2
  src/assets/fonts/roboto-light.woff
  src/assets/fonts/roboto-light.woff2
  src/assets/fonts/roboto-medium.woff
  src/assets/fonts/roboto-medium.woff2
  src/assets/fonts/roboto-regular.woff
  src/assets/fonts/roboto-regular.woff2
  src/assets/fonts/robotomono-bold.woff
  src/assets/fonts/robotomono-bold.woff2
  src/assets/fonts/robotomono-regular.woff
  src/assets/fonts/robotomono-regular.woff2
Labels: bug

#1674 chore: sort translation strings
  src/lang/locales/cs-CZ.js
  src/lang/locales/de-DE.js
  src/lang/locales/fr-FR.js
  src/lang/locales/it-IT.js
  src/lang/locales/ms-MY.js
  src/lang/locales/nl-NL.js
  src/lang/locales/pt-BR.js
  src/lang/locales/ru-RU.js
  src/lang/locales/zh-CN.js
Labels: optimization

#1676 Upgrade dependencies and remove fiber
  package-lock.json
  package.json
Labels: optimization

#1690 Add contextual menu component
  src/components/card.vue
  src/components/contextual-menu.vue
  src/components/header/header-button.vue
  src/components/v-contextual-menu.vue
  src/globals.js
  src/interfaces/many-to-many/display.vue
  src/interfaces/one-to-many/display.vue
  src/routes/item.vue
  src/routes/settings/fields.vue
Labels: enhancement

#1644 Storybook
  .gitignore
  .storybook/addons.js
  .storybook/config.js
  .storybook/directusTheme.js
  .storybook/manager-head.html
  .storybook/preview-head.html
  .storybook/storybook-reset.scss
  .storybook/webpack.config.js
  package-lock.json
  package.json
  src/components/card/card.vue
  src/components/form-inputs/button/button.readme.md
  src/components/form-inputs/button/button.stories.js
  src/components/form-inputs/button/button.vue
  src/globals.js
Labels: enhancement, optimization

#1692 Fix divider label showing.
  src/interfaces/divider/meta.json
Labels: bug

#1694 Align logout icon
  src/components/sidebars/nav-sidebar/user-menu.vue
Labels: bug

#1700 Upgrade dependencies
  package-lock.json
  package.json
Labels: optimization

#1703 Fixed #1702 - Slider interface fails on 0-value with negative minimum
  src/interfaces/slider/input.vue
Labels: bug

#1704 Fix package-lock
  package-lock.json
Labels: optimization
