Repository directus/app, pull requests merged in 2019-12, with the labels that each got.

#2276 Update options.vue
  src/layouts/cards/options.vue
Labels: bug

#2285 Use new system thumbnail sizes
  package-lock.json
  package.json
  src/api.js
  src/components/card/card.vue
  src/interfaces/file-preview/input.vue
  src/interfaces/file/input.vue
  src/interfaces/file/meta.json
  src/interfaces/files/input.vue
  src/layouts/cards/layout.vue
  src/layouts/cards/meta.json
  src/layouts/cards/options.vue
Labels: enhancement, tweak

#2286 Sanitize field name input
  src/components/field-setup.vue
Labels: bug

#2292 Add Icelandic language support
  src/lang/index.js
Labels: enhancement

#2310 Fix status when batch editing collections
  src/interfaces/status/input.vue
Labels: bug

#2322 Fix radio buttons interface + add placeholder to choices option
  src/interfaces/dropdown/meta.json
  src/interfaces/radio-buttons/meta.json
Labels: bug

#2324 Fix readonly state for languages / checkboxes interfaces
  src/components/form-inputs/checkbox.vue
  src/interfaces/checkboxes/input.vue
  src/interfaces/checkboxes/meta.json
  src/interfaces/language/input.vue
Labels: bug

#2333 Fetch related data if primary key is passed to m2o display component
  src/components/extension/interface/display/display.vue
  src/components/item-select/item-select.vue
  src/interfaces/many-to-one/display.vue
  src/interfaces/one-to-many/input.vue
Labels: bug

#2338 #1922 checkboxes-relational: Create / Update Sends only referenced PKs
  src/interfaces/checkboxes-relational/input.vue
Labels: bug, tweak

#2340 Fix settings/roles routing to wrong route on delete
  src/routes/settings/permissions.vue
Labels: bug

#2341 Rework translations interface
  src/interfaces/key-value/meta.json
  src/interfaces/translation/display.vue
  src/interfaces/translation/input.vue
  src/interfaces/translation/meta.json
  src/interfaces/wysiwyg/meta.json
  src/lang/en-US/index.json
  src/lang/en-US/interfaces.json
Labels: bug, enhancement

#2350 Default select-existing-file to desc sort on ID
  src/interfaces/file/input.vue
Labels: enhancement
