Repository directus/app, pull requests merged in 2019-06, with the labels that each got.

#1705 Removed a watch function on the advanced WYSIWYG editor.
  src/interfaces/wysiwyg-full/input.vue
Labels: bug

#1723 Lock version of webpack-dev-server
  package-lock.json
  package.json
Labels: optimization

#1724 Interface options interface
  src/components/form-inputs/select.vue
  src/interfaces/interface-options/display.vue
  src/interfaces/interface-options/input.vue
  src/interfaces/interface-options/meta.json
  src/interfaces/repeater/meta.json
  src/lang/locales/en-US.js
Labels: enhancement

#1725 Outline icons
  src/assets/fonts/material-icons-outline.woff2
  src/components/icon.vue
  src/design/_fonts.scss
Labels: enhancement

#1727 Add sup prop to v-icon
  src/components/icon.vue
Labels: enhancement

#1729 Fix styling of calendar dropdown
  src/interfaces/calendar/calendar.css
Labels: bug

#1728 Add field options dropdown
  src/components/contextual-menu.vue
  src/components/form/field.vue
  src/lang/locales/en-US.js
Labels: enhancement

#1731 Move the required asterisk left a bit
  src/components/form/field.vue
Labels: enhancement

#1677 Add item-select component for relational interfaces
  .eslintrc.js
  src/components/form-inputs/button/button.vue
  src/components/form/field.vue
  src/components/item-select/item-select.readme.md
  src/components/item-select/item-select.vue
  src/globals.js
  src/helpers/get-fields-from-template.js
  src/interfaces/many-to-one/input.vue
  src/interfaces/many-to-one/meta.json
  src/interfaces/one-to-many/input.vue
  src/interfaces/status/display.vue
  src/lang/locales/en-US.js
Labels: enhancement

#1733 Add ability to show / hide buttons + notice when no items selected
  src/interfaces/many-to-many/input.vue
  src/interfaces/many-to-many/meta.json
  src/interfaces/one-to-many/input.vue
  src/interfaces/one-to-many/meta.json
  src/lang/locales/en-US.js
Labels: enhancement

#1749 Fix map not working with repeater
  src/interfaces/map/input.vue
Labels: bug

#1750 clean up modal and text
  src/components/bookmarks/create-bookmark.vue
  src/lang/locales/cs-CZ.js
  src/lang/locales/de-DE.js
  src/lang/locales/en-US.js
  src/lang/locales/ms-MY.js
  src/lang/locales/pl-PL.js
Labels: tweak

#1751 text should never touch right of hover box
  src/components/sidebars/nav-sidebar/nav-menu.vue
Labels: tweak

#1758 Improve Repeater draggable
  src/interfaces/repeater/box.vue
  src/interfaces/repeater/input.vue
Labels: tweak

#1738 new interface filtering
  src/components/field-setup.vue
Labels: tweak

#1760 Fix unsupported regex
  src/helpers/get-fields-from-template.js
Labels: bug

#1763 Password type change
  src/interfaces/password/meta.json
  src/type-map.js
Labels: bug

#1772 Make calendar work with datetime field and fetch data according to current calendar view
  src/layouts/calendar/Day.vue
  src/layouts/calendar/Popup.vue
  src/layouts/calendar/layout.vue
  src/layouts/calendar/meta.json
  src/layouts/calendar/options.vue
Labels: bug, tweak

#1768 removes box, adds handle tooltip
  src/components/form-inputs/slider.vue
Labels: tweak

#1771 center map zoom button text
  src/interfaces/map/leaflet.css
Labels: tweak

#1770 font size and hr color
  src/interfaces/divider/input.vue
Labels: tweak

#1769 border to background color
  src/interfaces/icon/input.vue
Labels: tweak

#1765 Added checks if config is set correctly
  src/layouts/timeline/Day.vue
  src/layouts/timeline/Event.vue
  src/layouts/timeline/layout.vue
Labels: optimization

#1783 remove to delete icon
  src/routes/settings/fields.vue
Labels: tweak

#1774 Reimagine M2M
  package-lock.json
  package.json
  src/components/form/form.vue
  src/components/item-select/item-select.vue
  src/interfaces/many-to-many/input.vue
  src/interfaces/many-to-many/meta.json
  src/lang/locales/en-US.js
Labels: bug, enhancement

#1790 Default to the demo API when config is missing
  public/index.html
  src/main.js
Labels: tweak
