Repository directus/app, pull requests merged in 2020-02, with the labels that each got.

#2514 Add color support for hex and rgb
  src/layouts/calendar/layout.vue
Labels: enhancement

#2469 [WIP] v-table core component
  .jest/mount-composition.ts
  .storybook/main.js
  .storybook/webpack.config.js
  jest.config.js
  package.json
  src/components/v-table/_table-header.test.ts
  src/components/v-table/_table-header.vue
  src/components/v-table/_table-row.test.ts
  src/components/v-table/_table-row.vue
  src/components/v-table/index.ts
  src/components/v-table/types.ts
  src/components/v-table/v-table.readme.md
  src/components/v-table/v-table.story.ts
  src/components/v-table/v-table.test.ts
  src/components/v-table/v-table.vue
  src/compositions/event-listener.test.ts
  src/compositions/event-listener.ts
  src/design/_variables.scss
  src/lang/index.js
  src/main.js
  src/shim-md.d.ts
  src/shim-svg.d.ts
  src/shim-vue.d.ts
  src/shims.d.ts
  yarn.lock
Labels: enhancement, optimization, tweak

#2518 Add useWindowSize composition
  src/compositions/readme.md
  src/compositions/window-size.test.ts
  src/compositions/window-size.ts
Labels: enhancement

#2519 Add click event to v-overlay
  src/components/v-overlay/v-overlay.story.ts
  src/components/v-overlay/v-overlay.test.ts
  src/components/v-overlay/v-overlay.vue
Labels: enhancement

#2522 Use window instead of body as boundary element for v-popover
  src/interfaces/color/components/hex.vue
Labels: bug

#2521 Update index.json
  src/lang/es-419/index.json
Labels: tweak

#2530 Fix icon/switch alignments
  src/components/v-checkbox/v-checkbox.vue
  src/components/v-switch/v-switch.story.ts
  src/components/v-switch/v-switch.vue
  src/interfaces/switch/input.vue
  src/routes/settings/collections.vue
Labels: bug

#2532 Make vuedraggable globally available
  src/main.js
Labels: bug

#2524 Ajust align vertical on calendar
  src/layouts/calendar/Day.vue
Labels: bug, tweak

#2534 Remove auto_sign_out based idle tracking
  package.json
  src/hydrate.js
  src/idle.js
  yarn.lock
Labels: optimization, tweak

#2542 fix avatar input image height
  src/interfaces/owner/input.vue
Labels: bug

#2545 O2M tweaks
  src/interfaces/one-to-many/input.vue
Labels: bug

#2546 Permission style tweaks
  src/components/permissions/permissions.vue
Labels: bug, tweak

#2552 fixing link of lazy loaded items
  src/components/items.vue
Labels: bug

#2554 Handle webhooks collection in lazy loaded items
  src/components/items.vue
Labels: bug

#2558 Pass contextual primary key to nested m2m
  src/interfaces/many-to-many/input.vue
Labels: bug

#2560 Accept object based primary key values
  src/interfaces/file/input.vue
Labels: bug

#2561 Always show options tab on field-setup
  src/components/field-setup.vue
Labels: bug

#2564 Fix file select / upload in wysiwyg
  src/interfaces/file/input.vue
  src/interfaces/wysiwyg/input.vue
Labels: bug

#2565 Fix selecting users on the role detail page
  src/routes/settings/permissions.vue
Labels: bug

#2566 Fix link to the docs in install requirements
  src/components/install/requirements.vue
Labels: bug

#2567 Add missing label/comment for file crop option
  src/interfaces/file/meta.json
  src/lang/en-US/interfaces.json
Labels: bug

#2569 Truncate non-fitting field names + add tooltip
  src/routes/settings/fields.vue
Labels: bug

#2572 Contextual Menu with Header Button Positioning Issue
  .prettierrc
  src/components/contextual-menu.vue
  src/components/header/header-button.vue
Labels: bug, tweak

#2574 Console Error Fix with Icon Prop Type issue
  src/components/progress-ring.vue
Labels: bug

#2581 Replace v-timeago with time-from-now composition
  package.json
  src/components/activity/activity.vue
  src/components/time-ago.vue
  src/compositions/readme.md
  src/compositions/time-from-now.test.ts
  src/compositions/time-from-now.ts
  src/globals.js
  src/interfaces/calendar/display.vue
  src/interfaces/calendar/meta.json
  src/interfaces/calendar/types.ts
  src/interfaces/date/display.vue
  src/interfaces/date/types.ts
  src/interfaces/datetime-created/display.vue
  src/interfaces/datetime-created/input.vue
  src/interfaces/datetime-created/types.ts
  src/interfaces/datetime-updated/display.vue
  src/interfaces/datetime-updated/input.vue
  src/interfaces/datetime-updated/types.ts
  src/interfaces/datetime/display.vue
  src/interfaces/datetime/types.ts
  src/interfaces/time/display.vue
  src/lang/en-US/interfaces.json
  src/layouts/timeline/Event.vue
  src/main.js
  yarn.lock
Labels: bug, enhancement, release notice, tweak

#2582 Fix confirm modal cancel button styling
  src/components/modals/confirm.vue
Labels: bug

#2594 Style tweaks
  src/components/form-inputs/input.vue
  src/components/user-popover.vue
  src/components/v-button/v-button.vue
  src/components/v-icon/v-icon.readme.md
  src/components/v-icon/v-icon.story.ts
  src/components/v-icon/v-icon.test.ts
  src/components/v-icon/v-icon.vue
  src/interfaces/file/input.vue
  src/interfaces/files/input.vue
  src/interfaces/many-to-many/input.vue
  src/interfaces/one-to-many/input.vue
  src/interfaces/owner/input.vue
  src/interfaces/preview/input.vue
  src/interfaces/user-updated/input.vue
  src/routes/settings/collections.vue
Labels: tweak

#2608 Add readonly state to markdown interface
  src/interfaces/markdown/input.vue
Labels: bug

#2609 Only show signed toggle for numeric fields
  src/components/field-setup.vue
  src/lang/en-US/index.json
Labels: bug

#2618 Use switch interface as default interface for tinyint
  src/type-map.js
Labels: bug
