Repository directus/app, pull requests merged in 2020-01, with the labels that each got.

#2382 Fix placeholder for user-roles interface #2380
  src/interfaces/user-roles/input.vue
Labels: bug

#2363 Fix app #1885[Dropdown add other options]
  src/components/form-inputs/select.vue
  src/interfaces/dropdown/display.vue
  src/interfaces/dropdown/input.vue
  src/interfaces/dropdown/meta.json
  src/lang/en-US/interfaces.json
Labels: enhancement

#2370 fix #2366 correct singleItem collection title translation when editing
  src/routes/item.vue
Labels: bug

#2415 changed interface for multi-select to key-value (#2357)
  src/interfaces/README.md
  src/interfaces/multiselect/meta.json
Labels: bug

#2428 Fix label "Unsaved Changes" for languages on Modal Exit Form
  src/lang/en-US/index.json
  src/lang/es-419/index.json
  src/routes/item.vue
Labels: bug

#2433 Use window instead of body as boundary element for v-popover
  src/components/contextual-menu.vue
  src/main.js
Labels: bug

#2442 Fix button group rendering
  src/interfaces/button-group/input.vue
Labels: bug

#2443 New v-spinner component
  package.json
  src/components/extension/interface/display/display-loading.vue
  src/components/extension/interface/input/input-loading.vue
  src/components/extension/layout/layout/layout-loading.vue
  src/components/form-inputs/button/button.vue
  src/components/header/header-button.vue
  src/components/install/requirements.vue
  src/components/loader.vue
  src/components/permissions/permissions.vue
  src/components/public/notice.vue
  src/components/table/table.vue
  src/components/v-button/v-button.readme.md
  src/components/v-button/v-button.story.ts
  src/components/v-button/v-button.test.ts
  src/components/v-button/v-button.vue
  src/components/v-icon/v-icon.test.ts
  src/components/v-icon/v-icon.vue
  src/components/v-spinner/index.ts
  src/components/v-spinner/v-spinner.readme.md
  src/components/v-spinner/v-spinner.story.ts
  src/components/v-spinner/v-spinner.test.ts
  src/components/v-spinner/v-spinner.vue
  src/design/_variables.scss
  src/globals.js
  src/interfaces/many-to-one/input.vue
  src/layouts/timeline/layout.vue
  yarn.lock
Labels: optimization, tweak

#2141 Add "Download" option for file interface
  src/interfaces/file/input.vue
  src/lang/af-ZA/index.json
  src/lang/ar-SA/index.json
  src/lang/ca-ES/index.json
  src/lang/cs-CZ/index.json
  src/lang/da-DK/index.json
  src/lang/de-DE/index.json
  src/lang/el-GR/index.json
  src/lang/en-US/index.json
  src/lang/es-ES/index.json
  src/lang/fi-FI/index.json
  src/lang/fr-FR/index.json
  src/lang/he-IL/index.json
  src/lang/hu-HU/index.json
  src/lang/id-ID/index.json
  src/lang/it-IT/index.json
  src/lang/ja-JP/index.json
  src/lang/ko-KR/index.json
  src/lang/ms-MY/index.json
  src/lang/nl-NL/index.json
  src/lang/no-NO/index.json
  src/lang/pl-PL/index.json
  src/lang/pt-BR/index.json
  src/lang/pt-PT/index.json
  src/lang/ro-RO/index.json
  src/lang/ru-RU/index.json
  src/lang/sr-SP/index.json
  src/lang/sv-SE/index.json
  src/lang/tr-TR/index.json
  src/lang/uk-UA/index.json
  src/lang/vi-VN/index.json
  src/lang/zh-CN/index.json
  src/lang/zh-TW/index.json
Labels: enhancement

#2368 disable slug generate when editing, fix #2335
  src/interfaces/slug/input.vue
  src/interfaces/slug/meta.json
  src/lang/en-US/interfaces.json
Labels: bug, enhancement

#2452 Fix checkboxes + spinner on table
  src/components/extension/interface/display/display-loading.vue
  src/components/table/table.vue
Labels: bug

#2453 Add support for filename_download asset url naming
  src/components/extension/interface/input/input-loading.vue
  src/interfaces/file/input.vue
  src/layouts/cards/layout.vue
Labels: enhancement

#2455 Add overlay component
  src/components/v-overlay/index.ts
  src/components/v-overlay/v-overlay.readme.md
  src/components/v-overlay/v-overlay.story.ts
  src/components/v-overlay/v-overlay.test.ts
  src/components/v-overlay/v-overlay.vue
Labels: enhancement, optimization

#2458 Render color swatch for color interface
  src/interfaces/color/display.vue
Labels: bug

#2459 Prevent files interface from staging on first load
  src/interfaces/files/input.vue
Labels: bug

#2465 New v-avatar component
  src/components/avatar.vue
  src/components/form-inputs/button/button.readme.md
  src/components/form-inputs/button/button.vue
  src/components/sidebars/nav-sidebar/module-bar.vue
  src/components/user-popover.vue
  src/components/v-avatar/index.ts
  src/components/v-avatar/v-avatar.readme.md
  src/components/v-avatar/v-avatar.story.ts
  src/components/v-avatar/v-avatar.test.ts
  src/components/v-avatar/v-avatar.vue
  src/components/v-button/v-button.test.ts
  src/components/v-button/v-button.vue
  src/components/v-checkbox/v-checkbox.vue
  src/components/v-icon/v-icon.vue
  src/components/v-overlay/v-overlay.vue
  src/components/v-spinner/v-spinner.vue
  src/components/v-switch/v-switch.vue
  src/globals.js
  src/interfaces/owner/input.vue
  src/interfaces/user-updated/input.vue
Labels: enhancement

#2476 Add indeterminate state to v-checkbox base component
  src/components/v-checkbox/v-checkbox.readme.md
  src/components/v-checkbox/v-checkbox.story.ts
  src/components/v-checkbox/v-checkbox.test.ts
  src/components/v-checkbox/v-checkbox.vue
Labels: enhancement

#2477 Work around Netlify insecure warning
  .storybook/preview-head.html
Labels: optimization

#2478 Add new v-progress-linear component
  src/components/progress.vue
  src/components/v-progress/linear/index.ts
  src/components/v-progress/linear/v-progress-linear.readme.md
  src/components/v-progress/linear/v-progress-linear.test.ts
  src/components/v-progress/linear/v-progress-linear.vue
  src/components/v-progress/linear/v-progress.linear.story.ts
  src/globals.js
  src/interfaces/checkboxes/input.vue
  src/routes/install.vue
  src/routes/login.vue
  src/routes/setup-2fa.vue
Labels: optimization, tweak

#2483 Add hover HoC
  src/components/v-hover/index.ts
  src/components/v-hover/v-hover.readme.md
  src/components/v-hover/v-hover.story.ts
  src/components/v-hover/v-hover.test.ts
  src/components/v-hover/v-hover.vue
Labels: enhancement

#2480 Add fullscreen and directionality plugins to tinymce
  src/interfaces/wysiwyg/input.vue
  src/interfaces/wysiwyg/meta.json
Labels: enhancement

#2488 Add v-input base component
  src/components/v-input/index.ts
  src/components/v-input/v-input.readme.md
  src/components/v-input/v-input.story.ts
  src/components/v-input/v-input.test.ts
  src/components/v-input/v-input.vue
Labels: optimization, tweak

#2499 Fetch data in relational interfaces, instead of relying on parent
  package.json
  src/components/extension/interface/input/input.vue
  src/components/form/field.vue
  src/components/form/form.vue
  src/components/v-input/v-input.readme.md
  src/interfaces/checkboxes-relational/input.vue
  src/interfaces/file/input.vue
  src/interfaces/file/meta.json
  src/interfaces/files/input.vue
  src/interfaces/many-to-many/input.vue
  src/interfaces/one-to-many/input.vue
  src/interfaces/translation/input.vue
  src/lang/en-US/interfaces.json
  src/routes/item.vue
  src/routes/items.vue
  yarn.lock
Labels: bug, tweak

#2500 Fix icon grid on field setup
  src/components/field-setup.vue
Labels: bug

#2501 Ping on navigation instead of interval
  src/hydrate.js
  src/latency.js
  src/main.js
  src/router.js
Labels: tweak

#2486 [WIP] Add new v-slider component
  src/components/form-inputs/slider.vue
  src/components/v-slider/index.ts
  src/components/v-slider/v-slider.readme.md
  src/components/v-slider/v-slider.story.ts
  src/components/v-slider/v-slider.test.ts
  src/components/v-slider/v-slider.vue
  src/design/_variables.scss
Labels: optimization, tweak

#2507 Add click handler to v-icon
  src/components/v-icon/v-icon.readme.md
  src/components/v-icon/v-icon.story.ts
  src/components/v-icon/v-icon.test.ts
  src/components/v-icon/v-icon.vue
Labels: enhancement
