Repository directus/app, pull requests merged in 2020-05, with the labels that each got.

#2648 Fix filter parameter usage in item select component
  src/components/item-select/item-select.vue
Labels: bug

#2748 Allow external scripts access to modules used within Vue...
  src/main.js
Labels: enhancement

#2777 Feature: Add toggle all check box in item-select component
  src/components/item-select/item-select.vue
Labels: enhancement

#2779 Fix an issue where the column display would not be sorted in the field order.
  src/components/items.vue
Labels: enhancement

#2786 Fix infinite scroll
  src/components/items.vue
  src/routes/items.vue
Labels: bug

#2814 Use API-returned file urls
  src/components/public-view.vue
  src/components/sidebars/nav-sidebar/module-bar.vue
  src/interfaces/file-preview/input.vue
  src/interfaces/file/input.vue
  src/layouts/cards/layout.vue
Labels: bug, enhancement

#2836 Fix datetime display not handling iso8601
  src/interfaces/datetime-created/display.vue
  src/interfaces/datetime-updated/display.vue
Labels: bug

#2837 Fix value check in item select
  src/components/item-select/item-select.vue
Labels: bug
